name: Formatting

on:
  push:
  pull_request:

jobs:
  check-license-headers:
    runs-on: ubuntu-latest

    steps:
    - name: Check license headers
      uses: viperproject/check-license-header@v2
      with:
        path: ./screens
        config: /config.json
        strict: true